<?php
/**
 * @file
 * Custom article block module file.
 */
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Cache\Cache;

/**
 * Implements hook_entity_presave().
 */
function custom_article_block_entity_presave(EntityInterface $entity) {
  $type = $entity->getEntityType()->id();
  switch ($type) {
    case 'node':
      if ($entity->bundle() == 'article') {
        // Invalidate cache on product save.
        // $tags = ['article-section:' . (int) $entity->id()];
        // Cache::invalidateTags($tags);
      }

    break;
  }
}
/**
 * Implements hook_theme().
 */
function custom_article_block_theme() {
  return [
    'article_section_block' => [
      'variables' => [
        'articleData' => NULL,
      ],
    ],
  ];
}
